services:
  lingaro-azure-databricks-py312-ubuntu24:
    image: ${IMAGE}
    volumes:
      - ../:/workspaces:cached
    ports:
      - 8004:8000
    env_file:
      - ./.env
    environment:
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    command: /bin/bash -c "while sleep 1000; do :; done"
